version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass         # Rootユーザーのパスワード
      MYSQL_DATABASE: testdb                # 初期データベース名
      MYSQL_USER: javauser                  # アプリケーション用ユーザー
      MYSQL_PASSWORD: javapass              # アプリケーション用パスワード
    ports:
      - "3306:3306"                         # MySQLのポートをホストに公開
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 初期化SQLスクリプト
      - ./mysql_data:/var/lib/mysql                      # データ永続化ディレクトリ
    networks:
      - app-network

  tomcat:
    build: .                                 # Dockerfileがあるディレクトリ
    container_name: tomcat
    ports:
      - "8080:8080"                          # Tomcatのポートをホストに公開
    depends_on:
      - mysql                                # MySQLサービスの起動を待つ
    environment:
      DB_HOST: mysql                         # MySQLサービス名をホストとして指定
      DB_PORT: 3306
      DB_NAME: testdb
      DB_USER: javauser
      DB_PASSWORD: javapass
    networks:
      - app-network

networks:
  app-network:
    driver: bridge                           # ブリッジネットワークでコンテナ同士を接続
