name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # インストール確認

      - name: Build and start Docker containers
        run: |
          docker-compose up --build -d

      # Tomcatの起動を待つ
      - name: Wait for Tomcat to be ready
        run: |
          echo "Waiting for Tomcat to start..."
          for i in {1..10}; do
            if curl -s http://localhost:8080 > /dev/null; then
              echo "Tomcat is up!"
              break
            else
              echo "Tomcat is not up yet. Retrying in 5 seconds..."
              sleep 5
            fi
          done

      - name: Run tests
        run: |
          curl -f http://localhost:8080 || exit 1

      - name: Stop Docker containers
        run: docker-compose down
